name: vmlinux (5.10)

on:
  push:
    paths: '.github/workflows/vmlinux-5.10.yml'

permissions:
  contents: write

jobs:
  vmlinux:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: vmlinux
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install wget build-essential bison flex libncurses-dev libssl-dev libelf-dev
      - run: wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.180.tar.xz
      - run: tar xavf linux-5.10.180.tar.xz
      - run: git clone https://github.com/firecracker-microvm/firecracker
      - run: mv firecracker/resources/guest_configs/microvm-kernel-x86_64-5.10.config linux-5.10.180/.config
      - run: cd linux-5.10.180 && make vmlinux
      - run: find . -name "vmlinux*"
      - uses: softprops/action-gh-release@v1
        with:
          name: vmlinux-5.10
          tag_name: vmlinux-5.10
          files: vmlinux/linux-5.10.180/vmlinux
