name: vmlinux (5.10)

on:
  push:
    paths: '.github/workflows/vmlinux-5.10.yml'

jobs:
  vmlinux:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: vmlinux
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install wget build-essential bison flex libncurses-dev libssl-dev libelf-dev
      - run: wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.10.180.tar.xz
