name: vmlinux (5.10)

on:
  push:
    paths: '.github/workflows/vmlinux-5.10.yml'

jobs:
  vmlinux:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: vmlinux
    steps:
      - uses: actions/checkout@v2
